//! On-disk ext4 structures, transcribed from the Linux kernel (fs/ext4/ext4.h).
//! Field order and sizes must match the disk exactly: we cast raw bytes into
//! these structs with bytemuck, so a wrong offset means wrong data, not a crash.
//! Every multi-byte field is little-endian on disk regardless of the host.

#![allow(non_camel_case_types)]

use bytemuck::{Pod, Zeroable};

pub type __u8 = u8;
pub type __u16 = u16;
pub type __u32 = u32;
pub type __u64 = u64;
pub type __le16 = u16;
pub type __le32 = u32;
pub type __le64 = u64;

#[repr(C)]
#[derive(Debug, Copy, Clone, Pod, Zeroable)]
pub struct ext4_super_block {
    pub s_inodes_count: __le32,
    pub s_blocks_count_lo: __le32,
    pub s_r_blocks_count_lo: __le32,
    pub s_free_blocks_count_lo: __le32,
    pub s_free_inodes_count: __le32,
    pub s_first_data_block: __le32,
    pub s_log_block_size: __le32,
    pub s_log_cluster_size: __le32,
    pub s_blocks_per_group: __le32,
    pub s_clusters_per_group: __le32,
    pub s_inodes_per_group: __le32,
    pub s_mtime: __le32,
    pub s_wtime: __le32,
    pub s_mnt_count: __le16,
    pub s_max_mnt_count: __le16,
    pub s_magic: __le16,
    pub s_state: __le16,
    pub s_errors: __le16,
    pub s_minor_rev_level: __le16,
    pub s_lastcheck: __le32,
    pub s_checkinterval: __le32,
    pub s_creator_os: __le32,
    pub s_rev_level: __le32,
    pub s_def_resuid: __le16,
    pub s_def_resgid: __le16,
    pub s_first_ino: __le32,
    pub s_inode_size: __le16,
    pub s_block_group_nr: __le16,
    pub s_feature_compat: __le32,
    pub s_feature_incompat: __le32,
    pub s_feature_ro_compat: __le32,
    pub s_uuid: [__u8; 16],
    pub s_volume_name: [__u8; 16],
    pub s_last_mounted: [__u8; 64],
    pub s_algorithm_usage_bitmap: __le32,
    pub s_prealloc_blocks: __u8,
    pub s_prealloc_dir_blocks: __u8,
    pub s_reserved_gdt_blocks: __le16,
    pub s_journal_uuid: [__u8; 16],
    pub s_journal_inum: __le32,
    pub s_journal_dev: __le32,
    pub s_last_orphan: __le32,
    pub s_hash_seed: [__le32; 4],
    pub s_def_hash_version: __u8,
    pub s_jnl_backup_type: __u8,
    pub s_desc_size: __le16,
    pub s_default_mount_opts: __le32,
    pub s_first_meta_bg: __le32,
    pub s_mkfs_time: __le32,
    pub s_jnl_blocks: [__le32; 17],
    pub s_blocks_count_hi: __le32,
    pub s_r_blocks_count_hi: __le32,
    pub s_free_blocks_count_hi: __le32,
    pub s_min_extra_isize: __le16,
    pub s_want_extra_isize: __le16,
    pub s_flags: __le32,
    pub s_raid_stride: __le16,
    pub s_mmp_update_interval: __le16,
    pub s_mmp_block: __le64,
    pub s_raid_stripe_width: __le32,
    pub s_log_groups_per_flex: __u8,
    pub s_checksum_type: __u8,
    pub s_encryption_level: __u8,
    pub s_reserved_pad: __u8,
    pub s_kbytes_written: __le64,
    pub s_snapshot_inum: __le32,
    pub s_snapshot_id: __le32,
    pub s_snapshot_r_blocks_count: __le64,
    pub s_snapshot_list: __le32,
    pub s_error_count: __le32,
    pub s_first_error_time: __le32,
    pub s_first_error_ino: __le32,
    pub s_first_error_block: __le64,
    pub s_first_error_func: [__u8; 32],
    pub s_first_error_line: __le32,
    pub s_last_error_time: __le32,
    pub s_last_error_ino: __le32,
    pub s_last_error_line: __le32,
    pub s_last_error_block: __le64,
    pub s_last_error_func: [__u8; 32],
    pub s_mount_opts: [__u8; 64],
    pub s_usr_quota_inum: __le32,
    pub s_grp_quota_inum: __le32,
    pub s_overhead_clusters: __le32,
    pub s_backup_bgs: [__le32; 2],
    pub s_encrypt_algos: [__u8; 4],
    pub s_encrypt_pw_salt: [__u8; 16],
    pub s_lpf_ino: __le32,
    pub s_prj_quota_inum: __le32,
    pub s_checksum_seed: __le32,
    pub s_wtime_hi: __u8,
    pub s_mtime_hi: __u8,
    pub s_mkfs_time_hi: __u8,
    pub s_lastcheck_hi: __u8,
    pub s_first_error_time_hi: __u8,
    pub s_last_error_time_hi: __u8,
    pub s_pad: [__u8; 2],
    pub s_encoding: __le16,
    pub s_encoding_flags: __le16,
    pub s_reserved: [__le32; 95],
    pub s_checksum: __le32,
}

const _: () = assert!(core::mem::size_of::<ext4_super_block>() == 1024);
