/* automatically generated by rust-bindgen 0.72.1 */

use bytemuck::{Pod, Zeroable};

pub type __u8 = ::std::os::raw::c_uchar;
pub type __u16 = ::std::os::raw::c_ushort;
pub type __u32 = ::std::os::raw::c_uint;
pub type __u64 = ::std::os::raw::c_ulong;
pub type __le16 = __u16;
pub type __le32 = __u32;
pub type __le64 = __u64;
#[repr(C)]
#[derive(Debug, Copy, Clone, Pod, Zeroable)]
pub struct ext4_super_block {
    pub s_inodes_count: __le32,
    pub s_blocks_count_lo: __le32,
    pub s_r_blocks_count_lo: __le32,
    pub s_free_blocks_count_lo: __le32,
    pub s_free_inodes_count: __le32,
    pub s_first_data_block: __le32,
    pub s_log_block_size: __le32,
    pub s_log_cluster_size: __le32,
    pub s_blocks_per_group: __le32,
    pub s_clusters_per_group: __le32,
    pub s_inodes_per_group: __le32,
    pub s_mtime: __le32,
    pub s_wtime: __le32,
    pub s_mnt_count: __le16,
    pub s_max_mnt_count: __le16,
    pub s_magic: __le16,
    pub s_state: __le16,
    pub s_errors: __le16,
    pub s_minor_rev_level: __le16,
    pub s_lastcheck: __le32,
    pub s_checkinterval: __le32,
    pub s_creator_os: __le32,
    pub s_rev_level: __le32,
    pub s_def_resuid: __le16,
    pub s_def_resgid: __le16,
    pub s_first_ino: __le32,
    pub s_inode_size: __le16,
    pub s_block_group_nr: __le16,
    pub s_feature_compat: __le32,
    pub s_feature_incompat: __le32,
    pub s_feature_ro_compat: __le32,
    pub s_uuid: [__u8; 16usize],
    pub s_volume_name: [::std::os::raw::c_char; 16usize],
    pub s_last_mounted: [::std::os::raw::c_char; 64usize],
    pub s_algorithm_usage_bitmap: __le32,
    pub s_prealloc_blocks: __u8,
    pub s_prealloc_dir_blocks: __u8,
    pub s_reserved_gdt_blocks: __le16,
    pub s_journal_uuid: [__u8; 16usize],
    pub s_journal_inum: __le32,
    pub s_journal_dev: __le32,
    pub s_last_orphan: __le32,
    pub s_hash_seed: [__le32; 4usize],
    pub s_def_hash_version: __u8,
    pub s_jnl_backup_type: __u8,
    pub s_desc_size: __le16,
    pub s_default_mount_opts: __le32,
    pub s_first_meta_bg: __le32,
    pub s_mkfs_time: __le32,
    pub s_jnl_blocks: [__le32; 17usize],
    pub s_blocks_count_hi: __le32,
    pub s_r_blocks_count_hi: __le32,
    pub s_free_blocks_count_hi: __le32,
    pub s_min_extra_isize: __le16,
    pub s_want_extra_isize: __le16,
    pub s_flags: __le32,
    pub s_raid_stride: __le16,
    pub s_mmp_update_interval: __le16,
    pub s_mmp_block: __le64,
    pub s_raid_stripe_width: __le32,
    pub s_log_groups_per_flex: __u8,
    pub s_checksum_type: __u8,
    pub s_encryption_level: __u8,
    pub s_reserved_pad: __u8,
    pub s_kbytes_written: __le64,
    pub s_snapshot_inum: __le32,
    pub s_snapshot_id: __le32,
    pub s_snapshot_r_blocks_count: __le64,
    pub s_snapshot_list: __le32,
    pub s_error_count: __le32,
    pub s_first_error_time: __le32,
    pub s_first_error_ino: __le32,
    pub s_first_error_block: __le64,
    pub s_first_error_func: [__u8; 32usize],
    pub s_first_error_line: __le32,
    pub s_last_error_time: __le32,
    pub s_last_error_ino: __le32,
    pub s_last_error_line: __le32,
    pub s_last_error_block: __le64,
    pub s_last_error_func: [__u8; 32usize],
    pub s_mount_opts: [__u8; 64usize],
    pub s_usr_quota_inum: __le32,
    pub s_grp_quota_inum: __le32,
    pub s_overhead_clusters: __le32,
    pub s_backup_bgs: [__le32; 2usize],
    pub s_encrypt_algos: [__u8; 4usize],
    pub s_encrypt_pw_salt: [__u8; 16usize],
    pub s_lpf_ino: __le32,
    pub s_prj_quota_inum: __le32,
    pub s_checksum_seed: __le32,
    pub s_wtime_hi: __u8,
    pub s_mtime_hi: __u8,
    pub s_mkfs_time_hi: __u8,
    pub s_lastcheck_hi: __u8,
    pub s_first_error_time_hi: __u8,
    pub s_last_error_time_hi: __u8,
    pub s_pad: [__u8; 2usize],
    pub s_encoding: __le16,
    pub s_encoding_flags: __le16,
    pub s_reserved: [__le32; 95usize],
    pub s_checksum: __le32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext4_super_block"][::std::mem::size_of::<ext4_super_block>() - 1024usize];
    ["Alignment of ext4_super_block"][::std::mem::align_of::<ext4_super_block>() - 8usize];
    ["Offset of field: ext4_super_block::s_inodes_count"]
        [::std::mem::offset_of!(ext4_super_block, s_inodes_count) - 0usize];
    ["Offset of field: ext4_super_block::s_blocks_count_lo"]
        [::std::mem::offset_of!(ext4_super_block, s_blocks_count_lo) - 4usize];
    ["Offset of field: ext4_super_block::s_r_blocks_count_lo"]
        [::std::mem::offset_of!(ext4_super_block, s_r_blocks_count_lo) - 8usize];
    ["Offset of field: ext4_super_block::s_free_blocks_count_lo"]
        [::std::mem::offset_of!(ext4_super_block, s_free_blocks_count_lo) - 12usize];
    ["Offset of field: ext4_super_block::s_free_inodes_count"]
        [::std::mem::offset_of!(ext4_super_block, s_free_inodes_count) - 16usize];
    ["Offset of field: ext4_super_block::s_first_data_block"]
        [::std::mem::offset_of!(ext4_super_block, s_first_data_block) - 20usize];
    ["Offset of field: ext4_super_block::s_log_block_size"]
        [::std::mem::offset_of!(ext4_super_block, s_log_block_size) - 24usize];
    ["Offset of field: ext4_super_block::s_log_cluster_size"]
        [::std::mem::offset_of!(ext4_super_block, s_log_cluster_size) - 28usize];
    ["Offset of field: ext4_super_block::s_blocks_per_group"]
        [::std::mem::offset_of!(ext4_super_block, s_blocks_per_group) - 32usize];
    ["Offset of field: ext4_super_block::s_clusters_per_group"]
        [::std::mem::offset_of!(ext4_super_block, s_clusters_per_group) - 36usize];
    ["Offset of field: ext4_super_block::s_inodes_per_group"]
        [::std::mem::offset_of!(ext4_super_block, s_inodes_per_group) - 40usize];
    ["Offset of field: ext4_super_block::s_mtime"]
        [::std::mem::offset_of!(ext4_super_block, s_mtime) - 44usize];
    ["Offset of field: ext4_super_block::s_wtime"]
        [::std::mem::offset_of!(ext4_super_block, s_wtime) - 48usize];
    ["Offset of field: ext4_super_block::s_mnt_count"]
        [::std::mem::offset_of!(ext4_super_block, s_mnt_count) - 52usize];
    ["Offset of field: ext4_super_block::s_max_mnt_count"]
        [::std::mem::offset_of!(ext4_super_block, s_max_mnt_count) - 54usize];
    ["Offset of field: ext4_super_block::s_magic"]
        [::std::mem::offset_of!(ext4_super_block, s_magic) - 56usize];
    ["Offset of field: ext4_super_block::s_state"]
        [::std::mem::offset_of!(ext4_super_block, s_state) - 58usize];
    ["Offset of field: ext4_super_block::s_errors"]
        [::std::mem::offset_of!(ext4_super_block, s_errors) - 60usize];
    ["Offset of field: ext4_super_block::s_minor_rev_level"]
        [::std::mem::offset_of!(ext4_super_block, s_minor_rev_level) - 62usize];
    ["Offset of field: ext4_super_block::s_lastcheck"]
        [::std::mem::offset_of!(ext4_super_block, s_lastcheck) - 64usize];
    ["Offset of field: ext4_super_block::s_checkinterval"]
        [::std::mem::offset_of!(ext4_super_block, s_checkinterval) - 68usize];
    ["Offset of field: ext4_super_block::s_creator_os"]
        [::std::mem::offset_of!(ext4_super_block, s_creator_os) - 72usize];
    ["Offset of field: ext4_super_block::s_rev_level"]
        [::std::mem::offset_of!(ext4_super_block, s_rev_level) - 76usize];
    ["Offset of field: ext4_super_block::s_def_resuid"]
        [::std::mem::offset_of!(ext4_super_block, s_def_resuid) - 80usize];
    ["Offset of field: ext4_super_block::s_def_resgid"]
        [::std::mem::offset_of!(ext4_super_block, s_def_resgid) - 82usize];
    ["Offset of field: ext4_super_block::s_first_ino"]
        [::std::mem::offset_of!(ext4_super_block, s_first_ino) - 84usize];
    ["Offset of field: ext4_super_block::s_inode_size"]
        [::std::mem::offset_of!(ext4_super_block, s_inode_size) - 88usize];
    ["Offset of field: ext4_super_block::s_block_group_nr"]
        [::std::mem::offset_of!(ext4_super_block, s_block_group_nr) - 90usize];
    ["Offset of field: ext4_super_block::s_feature_compat"]
        [::std::mem::offset_of!(ext4_super_block, s_feature_compat) - 92usize];
    ["Offset of field: ext4_super_block::s_feature_incompat"]
        [::std::mem::offset_of!(ext4_super_block, s_feature_incompat) - 96usize];
    ["Offset of field: ext4_super_block::s_feature_ro_compat"]
        [::std::mem::offset_of!(ext4_super_block, s_feature_ro_compat) - 100usize];
    ["Offset of field: ext4_super_block::s_uuid"]
        [::std::mem::offset_of!(ext4_super_block, s_uuid) - 104usize];
    ["Offset of field: ext4_super_block::s_volume_name"]
        [::std::mem::offset_of!(ext4_super_block, s_volume_name) - 120usize];
    ["Offset of field: ext4_super_block::s_last_mounted"]
        [::std::mem::offset_of!(ext4_super_block, s_last_mounted) - 136usize];
    ["Offset of field: ext4_super_block::s_algorithm_usage_bitmap"]
        [::std::mem::offset_of!(ext4_super_block, s_algorithm_usage_bitmap) - 200usize];
    ["Offset of field: ext4_super_block::s_prealloc_blocks"]
        [::std::mem::offset_of!(ext4_super_block, s_prealloc_blocks) - 204usize];
    ["Offset of field: ext4_super_block::s_prealloc_dir_blocks"]
        [::std::mem::offset_of!(ext4_super_block, s_prealloc_dir_blocks) - 205usize];
    ["Offset of field: ext4_super_block::s_reserved_gdt_blocks"]
        [::std::mem::offset_of!(ext4_super_block, s_reserved_gdt_blocks) - 206usize];
    ["Offset of field: ext4_super_block::s_journal_uuid"]
        [::std::mem::offset_of!(ext4_super_block, s_journal_uuid) - 208usize];
    ["Offset of field: ext4_super_block::s_journal_inum"]
        [::std::mem::offset_of!(ext4_super_block, s_journal_inum) - 224usize];
    ["Offset of field: ext4_super_block::s_journal_dev"]
        [::std::mem::offset_of!(ext4_super_block, s_journal_dev) - 228usize];
    ["Offset of field: ext4_super_block::s_last_orphan"]
        [::std::mem::offset_of!(ext4_super_block, s_last_orphan) - 232usize];
    ["Offset of field: ext4_super_block::s_hash_seed"]
        [::std::mem::offset_of!(ext4_super_block, s_hash_seed) - 236usize];
    ["Offset of field: ext4_super_block::s_def_hash_version"]
        [::std::mem::offset_of!(ext4_super_block, s_def_hash_version) - 252usize];
    ["Offset of field: ext4_super_block::s_jnl_backup_type"]
        [::std::mem::offset_of!(ext4_super_block, s_jnl_backup_type) - 253usize];
    ["Offset of field: ext4_super_block::s_desc_size"]
        [::std::mem::offset_of!(ext4_super_block, s_desc_size) - 254usize];
    ["Offset of field: ext4_super_block::s_default_mount_opts"]
        [::std::mem::offset_of!(ext4_super_block, s_default_mount_opts) - 256usize];
    ["Offset of field: ext4_super_block::s_first_meta_bg"]
        [::std::mem::offset_of!(ext4_super_block, s_first_meta_bg) - 260usize];
    ["Offset of field: ext4_super_block::s_mkfs_time"]
        [::std::mem::offset_of!(ext4_super_block, s_mkfs_time) - 264usize];
    ["Offset of field: ext4_super_block::s_jnl_blocks"]
        [::std::mem::offset_of!(ext4_super_block, s_jnl_blocks) - 268usize];
    ["Offset of field: ext4_super_block::s_blocks_count_hi"]
        [::std::mem::offset_of!(ext4_super_block, s_blocks_count_hi) - 336usize];
    ["Offset of field: ext4_super_block::s_r_blocks_count_hi"]
        [::std::mem::offset_of!(ext4_super_block, s_r_blocks_count_hi) - 340usize];
    ["Offset of field: ext4_super_block::s_free_blocks_count_hi"]
        [::std::mem::offset_of!(ext4_super_block, s_free_blocks_count_hi) - 344usize];
    ["Offset of field: ext4_super_block::s_min_extra_isize"]
        [::std::mem::offset_of!(ext4_super_block, s_min_extra_isize) - 348usize];
    ["Offset of field: ext4_super_block::s_want_extra_isize"]
        [::std::mem::offset_of!(ext4_super_block, s_want_extra_isize) - 350usize];
    ["Offset of field: ext4_super_block::s_flags"]
        [::std::mem::offset_of!(ext4_super_block, s_flags) - 352usize];
    ["Offset of field: ext4_super_block::s_raid_stride"]
        [::std::mem::offset_of!(ext4_super_block, s_raid_stride) - 356usize];
    ["Offset of field: ext4_super_block::s_mmp_update_interval"]
        [::std::mem::offset_of!(ext4_super_block, s_mmp_update_interval) - 358usize];
    ["Offset of field: ext4_super_block::s_mmp_block"]
        [::std::mem::offset_of!(ext4_super_block, s_mmp_block) - 360usize];
    ["Offset of field: ext4_super_block::s_raid_stripe_width"]
        [::std::mem::offset_of!(ext4_super_block, s_raid_stripe_width) - 368usize];
    ["Offset of field: ext4_super_block::s_log_groups_per_flex"]
        [::std::mem::offset_of!(ext4_super_block, s_log_groups_per_flex) - 372usize];
    ["Offset of field: ext4_super_block::s_checksum_type"]
        [::std::mem::offset_of!(ext4_super_block, s_checksum_type) - 373usize];
    ["Offset of field: ext4_super_block::s_encryption_level"]
        [::std::mem::offset_of!(ext4_super_block, s_encryption_level) - 374usize];
    ["Offset of field: ext4_super_block::s_reserved_pad"]
        [::std::mem::offset_of!(ext4_super_block, s_reserved_pad) - 375usize];
    ["Offset of field: ext4_super_block::s_kbytes_written"]
        [::std::mem::offset_of!(ext4_super_block, s_kbytes_written) - 376usize];
    ["Offset of field: ext4_super_block::s_snapshot_inum"]
        [::std::mem::offset_of!(ext4_super_block, s_snapshot_inum) - 384usize];
    ["Offset of field: ext4_super_block::s_snapshot_id"]
        [::std::mem::offset_of!(ext4_super_block, s_snapshot_id) - 388usize];
    ["Offset of field: ext4_super_block::s_snapshot_r_blocks_count"]
        [::std::mem::offset_of!(ext4_super_block, s_snapshot_r_blocks_count) - 392usize];
    ["Offset of field: ext4_super_block::s_snapshot_list"]
        [::std::mem::offset_of!(ext4_super_block, s_snapshot_list) - 400usize];
    ["Offset of field: ext4_super_block::s_error_count"]
        [::std::mem::offset_of!(ext4_super_block, s_error_count) - 404usize];
    ["Offset of field: ext4_super_block::s_first_error_time"]
        [::std::mem::offset_of!(ext4_super_block, s_first_error_time) - 408usize];
    ["Offset of field: ext4_super_block::s_first_error_ino"]
        [::std::mem::offset_of!(ext4_super_block, s_first_error_ino) - 412usize];
    ["Offset of field: ext4_super_block::s_first_error_block"]
        [::std::mem::offset_of!(ext4_super_block, s_first_error_block) - 416usize];
    ["Offset of field: ext4_super_block::s_first_error_func"]
        [::std::mem::offset_of!(ext4_super_block, s_first_error_func) - 424usize];
    ["Offset of field: ext4_super_block::s_first_error_line"]
        [::std::mem::offset_of!(ext4_super_block, s_first_error_line) - 456usize];
    ["Offset of field: ext4_super_block::s_last_error_time"]
        [::std::mem::offset_of!(ext4_super_block, s_last_error_time) - 460usize];
    ["Offset of field: ext4_super_block::s_last_error_ino"]
        [::std::mem::offset_of!(ext4_super_block, s_last_error_ino) - 464usize];
    ["Offset of field: ext4_super_block::s_last_error_line"]
        [::std::mem::offset_of!(ext4_super_block, s_last_error_line) - 468usize];
    ["Offset of field: ext4_super_block::s_last_error_block"]
        [::std::mem::offset_of!(ext4_super_block, s_last_error_block) - 472usize];
    ["Offset of field: ext4_super_block::s_last_error_func"]
        [::std::mem::offset_of!(ext4_super_block, s_last_error_func) - 480usize];
    ["Offset of field: ext4_super_block::s_mount_opts"]
        [::std::mem::offset_of!(ext4_super_block, s_mount_opts) - 512usize];
    ["Offset of field: ext4_super_block::s_usr_quota_inum"]
        [::std::mem::offset_of!(ext4_super_block, s_usr_quota_inum) - 576usize];
    ["Offset of field: ext4_super_block::s_grp_quota_inum"]
        [::std::mem::offset_of!(ext4_super_block, s_grp_quota_inum) - 580usize];
    ["Offset of field: ext4_super_block::s_overhead_clusters"]
        [::std::mem::offset_of!(ext4_super_block, s_overhead_clusters) - 584usize];
    ["Offset of field: ext4_super_block::s_backup_bgs"]
        [::std::mem::offset_of!(ext4_super_block, s_backup_bgs) - 588usize];
    ["Offset of field: ext4_super_block::s_encrypt_algos"]
        [::std::mem::offset_of!(ext4_super_block, s_encrypt_algos) - 596usize];
    ["Offset of field: ext4_super_block::s_encrypt_pw_salt"]
        [::std::mem::offset_of!(ext4_super_block, s_encrypt_pw_salt) - 600usize];
    ["Offset of field: ext4_super_block::s_lpf_ino"]
        [::std::mem::offset_of!(ext4_super_block, s_lpf_ino) - 616usize];
    ["Offset of field: ext4_super_block::s_prj_quota_inum"]
        [::std::mem::offset_of!(ext4_super_block, s_prj_quota_inum) - 620usize];
    ["Offset of field: ext4_super_block::s_checksum_seed"]
        [::std::mem::offset_of!(ext4_super_block, s_checksum_seed) - 624usize];
    ["Offset of field: ext4_super_block::s_wtime_hi"]
        [::std::mem::offset_of!(ext4_super_block, s_wtime_hi) - 628usize];
    ["Offset of field: ext4_super_block::s_mtime_hi"]
        [::std::mem::offset_of!(ext4_super_block, s_mtime_hi) - 629usize];
    ["Offset of field: ext4_super_block::s_mkfs_time_hi"]
        [::std::mem::offset_of!(ext4_super_block, s_mkfs_time_hi) - 630usize];
    ["Offset of field: ext4_super_block::s_lastcheck_hi"]
        [::std::mem::offset_of!(ext4_super_block, s_lastcheck_hi) - 631usize];
    ["Offset of field: ext4_super_block::s_first_error_time_hi"]
        [::std::mem::offset_of!(ext4_super_block, s_first_error_time_hi) - 632usize];
    ["Offset of field: ext4_super_block::s_last_error_time_hi"]
        [::std::mem::offset_of!(ext4_super_block, s_last_error_time_hi) - 633usize];
    ["Offset of field: ext4_super_block::s_pad"]
        [::std::mem::offset_of!(ext4_super_block, s_pad) - 634usize];
    ["Offset of field: ext4_super_block::s_encoding"]
        [::std::mem::offset_of!(ext4_super_block, s_encoding) - 636usize];
    ["Offset of field: ext4_super_block::s_encoding_flags"]
        [::std::mem::offset_of!(ext4_super_block, s_encoding_flags) - 638usize];
    ["Offset of field: ext4_super_block::s_reserved"]
        [::std::mem::offset_of!(ext4_super_block, s_reserved) - 640usize];
    ["Offset of field: ext4_super_block::s_checksum"]
        [::std::mem::offset_of!(ext4_super_block, s_checksum) - 1020usize];
};
